### ISSUE TITLE
Other Platform

### ISSUE THREAD

**Issue by raselldev** [ramcona/Ngidol48#1]
Dear om ramcona,

Boleh ga API yang ada diaplikasi ini saya pakai kembali? Saya mau coba untuk buat kembali dengan menggunakan .NET Maui sebagai frontend nya.

**Comment by ramcona** [comment]
boleh sekali mas

**Comment by raselldev** [comment]
Thankyou. Saya coba yah

**Comment by ramcona** [comment]
saya ada dokumentasi APInya di postman, mungkin bisa email ke rafliramadhanco@gmail.com untuk saya kirim collectionnya

**Comment by raselldev** [comment]
Sudah saya email. Thankyou

**Comment by visoredkon** [comment]
> saya ada dokumentasi APInya di postman, mungkin bisa email ke [rafliramadhanco@gmail.com](mailto:rafliramadhanco@gmail.com) untuk saya kirim collectionnya

Hallo kak @ramcona saya juga tertarik untuk memakai APInya kembali, apakah boleh? Saya juga sudah email ya kak. Terima kasih sebelumnya 🙏
